#!/bin/bash

PROPERTIES=${slack_bot_home:-.}/application.properties

load_properties() {
    file=$PROPERTIES
    if [ -f "$file" ]
    then
        echo "$file found."
        while IFS='=' read -r key value
        do
            key=$(echo $key | tr '.' '_')
            eval "${key}='${value}'"
        done < "$file"
    else
        echo "$file not found."
    fi
}

send_slack_message() {
    curl --silent --request POST \
        --url "${slack_hooks}"  \
        --data "{\"text\":\"$1\"}"
}

create_post() {
    title="$1" message="$2" tags="$3" ${slack_bot_home}/post > "${github_repo}/_posts/$(date "+%Y-%m-%d")-${1//[ ]/-}.md"
}


commit_post() {
    cd "${github_repo}"
#    git add .
#    git commit -m "$1 added"
}

build_message() {
    title="${1}"
    text="${2}"
    tags="${3}"
    room="${4}"
    next_date=`date "+%Y-%m-%d"`
    message=`text="${text}" room="${room}" ${slack_bot_home}/message`
    echo "${message}"
}

create() {
    title="${1}"
    text="${2}"
    tags="${3}"
    room="${4}"

    message=`build_message "${title}" "${text}" "${tags}" "${room}" `

    create_post "${title}" "${message}" "${tags}"
    commit_post "${title}"
}

update() {
    echo "Not supported yet"
}

send() {
    title="${1}"
    text="${2}"
    tags="${3}"
    room="${4}"

    message=`build_message "${title}" "${text}" "${tags}" "${room}" `

    send_slack_message "${message}\nSee updates at ${githubio_path}"
}

load_properties

case "$1" in
    'create')
            create "$2" "$3" "$4" "$5"
            ;;
    'update')
            update "$2" "$3" "$4" "$5"
            ;;
    'send')
            send "$2" "$3" "$4" "$5"
            ;;
    *)
            echo
            echo "Usage: $0 { create | update | send } title message"
            echo
            exit 1
            ;;
esac

exit 0
