#!/bin/bash

PROPERTIES=${slack_bot_home:-.}/application.properties

load_properties() {
    file="${PROPERTIES}"
    if [ -f "$file" ]
    then
        echo "$file found."
        while IFS='=' read -r key value
        do
            key=$(echo ${key} | tr '.' '_')
            eval "${key}='${value}'"
        done < "$file"
    else
        echo "$file not found."
    fi
}

send_slack_message() {
    message="${1}"
    curl --silent --request POST \
        --url "${slack_hooks}"  \
        --data "{\"text\":\"${message}\"}"
}

create_post() {
    title="${1}"
    message="${2}"
    image_url="${3}"
    tags="${4}"

    title="${title}" message="${message}" image_url="${image_url}" tags="${tags}" \
        ${slack_bot_home}/post > "${github_repo}/_posts/$(date "+%Y-%m-%d")-${1//[ #]/-}.md"
}


commit_post() {
    message="${1}"
    cd "${github_repo}"
    git add .
    git commit -m "${message} added"
}

build_post_message() {
    title="${1}"
    text="${2}"
    room="${3}"
    details_url="${4}"

    next_date=`date "+%Y-%m-%d"`
    message=`text="${text}" room="${room}" details_url="${details_url}" ${slack_bot_home}/post_message`
    echo "${message}"
}

build_slack_message() {
    title="${1}"
    text="${2}"
    room="${3}"
    details_url="${4}"

    next_date=`date "+%Y-%m-%d"`
    message=`text="${text}" room="${room}" details_url="${details_url}" ${slack_bot_home}/slack_message`
    echo "${message}"
}

create() {
    title="${1}"
    text="${2}"
    room="${3}"
    details_url="${4}"
    image_url="${5}"
    tags="${6}"

    message=`build_post_message "${title}" "${text}" "${room}" "${details_url}"`

    create_post "${title}" "${message}" "${image_url}" "${tags}"
    commit_post "${title}"
}

wait_for_post() {
    url=${githubio_path}/$(date "+%Y/%m/%d")/${1//[ #]/-}.html
    echo "Waiting for post $url";
    until $(curl --output /dev/null --silent --head --fail "$url"); do
      printf '.'
      sleep 5
    done
}

update() {
    echo "Not supported yet"
}

send() {
    title="${1}"
    text="${2}"
    room="${3}"
    details_url="${4}"

    message=`build_slack_message "${title}" "${text}" "${room}" "${details_url}"`

    send_slack_message "${message}\nSee updates at ${githubio_path}"
}

load_properties

program="${0}"
command="${1}"

title="${2}"
text="${3}"
room="${4}"
details_url="${5}"
image_url="${6}"
tags="${7}"

case "${command}" in
    'create')
            create "${title}" "${text}" "${room}" "${details_url}" "${image_url}" "${tags}"
            ;;
    'update')
            update
            ;;
    'wait-for-post')
            wait_for_post "${title}"
            ;;
    'send')
            send "${title}" "${text}" "${room}" "${details_url}"
            ;;
    *)
            echo
            echo "Usage: ${program} { create | update | send } title message tags room"
            echo
            exit 1
            ;;
esac

exit 0
