#!/bin/bash

PROPERTIES=${slack_bot_home:-.}/application.properties

load_properties() {
    file="${PROPERTIES}"
    if [ -f "$file" ]
    then
        echo "$file found."
        while IFS='=' read -r key value
        do
            key=$(echo ${key} | tr '.' '_')
            eval "${key}='${value}'"
        done < "$file"
    else
        echo "$file not found."
    fi
}

send_slack_message() {
    message="${1}"
    curl --silent --request POST \
        --url "${slack_hooks}"  \
        --data "{\"text\":\"${message}\"}"
}

create_post() {
    title="$1" message="$2" tags="$3" ${slack_bot_home}/post > "${github_repo}/_posts/$(date "+%Y-%m-%d")-${1//[ ]/-}.md"
}


commit_post() {
    message="${1}"
    cd "${github_repo}"
    git add .
    git commit -m "${message} added"
}

build_message() {
    title="${1}"
    text="${2}"
    room="${3}"
    next_date=`date "+%Y-%m-%d"`
    message=`text="${text}" room="${room}" ${slack_bot_home}/message`
    echo "${message}"
}

create() {
    title="${1}"
    text="${2}"
    tags="${3}"
    room="${4}"

    message=`build_message "${title}" "${text}" "${room}" `

    create_post "${title}" "${message}" "${tags}"
    commit_post "${title}"
}

wait_for_post() {
    url=${githubio_path}/$(date "+%Y/%m/%d")/${1//[ ]/-}.html
    echo "Waiting for post $url";
    until $(curl --output /dev/null --silent --head --fail "$url"); do
      printf '.'
      sleep 5
    done
}

create() {
    title="${1}"
    text="${2}"
    tags="${3}"
    next_date=`date "+%Y-%m-%d"`
    message=`text="${text}" ./message`

    create_post "${title}" "${message}" "${tags}"
    push_post "${title}"
    waiting_post "${title}"

    send "${message}\nSee updates at ${github_io}"
}

update() {
    echo "Not supported yet"
}

send() {
    title="${1}"
    text="${2}"
    room="${3}"

    message=`build_message "${title}" "${text}" "${room}" `

    send_slack_message "${message}\nSee updates at ${githubio_path}"
}

load_properties

program="${0}"
command="${1}"
title="${2}"
text="${3}"
tags="${4}"
room="${5}"

case "${command}" in
    'create')
            create "${title}" "${text}" "${tags}" "${room}"
            ;;
    'update')
            update
            ;;
    'wait-for-post')
            wait_for_post "${title}"
            ;;
    'send')
            send "${title}" "${text}" "${room}"
            ;;
    *)
            echo
            echo "Usage: ${program} { create | update | send } title message tags room"
            echo
            exit 1
            ;;
esac

exit 0
